---
- name: Install jupyetr lab
  hosts: all
  become: yes 
  vars:
    jupyter_port: "{{ lookup('env', 'JUPYTER_PORT') | default('14500', true) }}"
    jupyter_user: "{{ lookup('env', 'JUPYTER_USER') | default('jupusr', true) }}"
  tasks:
    - name: jupyter_user create or exists
      ansible.builtin.user:
        name: "{{ jupyter_user }}"
        state: present
        create_home: yes
        shell: /bin/bash
      become: yes

    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - python3-pip
          - python3-venv
          #- python3-dev
          #- build-essential
        state: present
        update_cache: yes
      become: yes


    - name: Create virtual environment and install Jupyter Lab
      ansible.builtin.shell: |
        python3 -m venv /home/jupusr/jupyterlab_env
        /home/{{ jupyter_user }}/jupyterlab_env/bin/pip install --upgrade pip
        /home/{{ jupyter_user }}/jupyterlab_env/bin/pip install jupyterlab
        /home/{{ jupyter_user }}/jupyterlab_env/bin/jupyter lab --generate-config
      become: yes
      become_user: "{{ jupyter_user }}"
      args:
        creates: /home/{{ jupyter_user }}/jupyterlab_env/bin/jupyter  #Если файл уже есть, не выполнять заново


    - name: Configure Jupyter Lab server settings
      ansible.builtin.blockinfile:
        path: /home/{{ jupyter_user }}/.jupyter/jupyter_lab_config.py
        block: |
          c.ServerApp.ip = "0.0.0.0"
          c.ServerApp.port = {{ jupyter_user }}
          c.ServerApp.open_browser = False
          c.ServerApp.token = ''
          c.ServerApp.password = ''
        insertafter: BOF
        create: no
        #owner: jupusr
        #group: jupusr
        #mode: '0644'
      become: yes
      become_user: jupusr


    - name: Create Jupyter Lab systemd service file
      ansible.builtin.blockinfile:
        path: /etc/systemd/system/jupyterlab.service
        block: |
          [Unit]
          Description=Jupyter Lab Service
          After=network.target

          [Service]
          Type=simple
          User={{ jupyter_user }}
          WorkingDirectory=/home/{{ jupyter_user }}/jupyterlab_env
          Environment="PATH=/home/{{ jupyter_user }}/jupyterlab_env/bin:/usr/local/bin:/usr/bin:/bin"
          ExecStart=/home/{{ jupyter_user }}/jupyterlab_env/bin/jupyter lab
          Restart=always
          RestartSec=10

          [Install]
          WantedBy=multi-user.target
        insertafter: BOF
        create: yes
        mode: '0644'
      become: yes
      notify: restart jupyterlab


    - name: Enable and start Jupyter Lab
      ansible.builtin.systemd:
        name: jupyterlab
        enabled: yes
        state: started
        daemon_reload: yes
      become: yes

  handlers:
    - name: restart jupyterlab
      ansible.builtin.systemd:
        name: jupyterlab
        state: restarted
        daemon_reload: yes
      become: yes
