name: Molecule Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Molecule
        uses: bec-galaxy/setup-molecule@v1

      - name: Install Molecule Docker driver
        run: pip install molecule-docker

      - name: Run Molecule tests
        run: molecule test -s ci
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
