name: Molecule Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  molecule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ansible collection for Podman
        run: ansible-galaxy collection install containers.podman
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install molecule molecule-docker ansible-lint
          pip install "molecule-plugins[podman]"

      - name: Install Molecule Docker driver
        run: pip install molecule-docker

      - name: Run Molecule tests (ci scenario)
        run: molecule test -s ci
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
